# Generated by Django 3.2.7 on 2021-12-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('year_of_pub', models.CharField(max_length=4)),
                ('isbn', models.CharField(max_length=13)),
                ('quantity', models.CharField(max_length=5)),
                ('unit_price', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('edition', models.CharField(max_length=10)),
                ('total_price', models.CharField(max_length=10)),
                ('net_price', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('LB', 'Library'), ('IT', 'IT'), ('HR', 'HR'), ('TC', 'Teaching')], default='LB', max_length=2)),
                ('mode', models.CharField(choices=[('PR', 'Purchase'), ('BR', 'Borrow')], default='PR', max_length=2)),
                ('location', models.CharField(choices=[('BF', 'Bookfair'), ('SW', 'Somewhere')], default='BF', max_length=2)),
                ('date', models.DateField()),
                ('budget', models.CharField(max_length=10)),
                ('recom_by', models.CharField(choices=[('TA', 'Prof Tan'), ('AD', 'Dr. Advincula')], default='TA', max_length=2)),
                ('type', models.CharField(choices=[('BO', 'Book'), ('LT', 'Letter')], default='BO', max_length=2)),
                ('status', models.CharField(choices=[('AC', 'Acquired'), ('BT', 'Bought')], default='AC', max_length=2)),
                ('dealer', models.CharField(choices=[('FF', 'Forefront'), ('UF', 'Upfront')], default='FF', max_length=2)),
            ],
        ),
    ]
