# Generated by Django 3.2.7 on 2021-10-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title_proper', models.CharField(max_length=255)),
                ('responsibility', models.CharField(max_length=255)),
                ('preferred_title', models.CharField(max_length=255)),
                ('parallel_title', models.CharField(max_length=255)),
                ('main_creator', models.CharField(max_length=255)),
                ('added_entry_creator', models.CharField(max_length=255)),
                ('contributors', models.CharField(max_length=255)),
                ('added_entry_corporate', models.CharField(max_length=255)),
                ('place_of_publication', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('date_of_publication', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='TitleProper',
        ),
    ]
