# Generated by Django 3.2.7 on 2021-10-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_auto_20211001_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_of_publication',
        ),
    ]
