# Generated by Django 3.2.7 on 2021-12-22 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_acquisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
