# Generated by Django 3.2.7 on 2021-12-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_acquisition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='accession',
            field=models.CharField(max_length=15),
        ),
    ]
